**==================== Numpy Random ====================**

In [1]:
import numpy as np
from numpy import random

In [2]:
random.rand()

0.21840544712355858

In [3]:
random.rand(5)

array([0.38820171, 0.01836937, 0.08836052, 0.5463684 , 0.62117964])

In [4]:
random.rand(3, 5)

array([[0.29395085, 0.49171766, 0.74691995, 0.86705719, 0.0049136 ],
       [0.40825827, 0.67268194, 0.94450778, 0.46936056, 0.37941249],
       [0.48171862, 0.51202287, 0.94743703, 0.7893522 , 0.26946371]])

In [5]:
random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

3

In [6]:
random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], size= (3, 5))

array([[7, 7, 8, 8, 9],
       [5, 3, 5, 5, 5],
       [2, 6, 5, 6, 7]])

In [7]:
random.randint(100)

96

In [8]:
random.randint(100, size= (5))

array([97, 56, 76, 95, 73])

In [9]:
random.randint(100, size= (3, 5))

array([[61, 17, 44, 42, 21],
       [22, 17, 89, 70, 70],
       [32, 91, 60, 24, 44]])

In [10]:
random.normal(loc= 1, scale= 2, size= (2, 3))

array([[-0.52106923,  3.18698092,  2.3814332 ],
       [ 2.09811325,  3.89426155,  0.6074976 ]])

In [11]:
random.normal(loc= 1, scale= 6, size= (2, 3))

array([[ 5.81790287, 14.99756952, -3.92991923],
       [-5.11341613,  2.37574978,  1.69033999]])

In [12]:
random.normal(loc= 5, scale= 2, size= (2, 3))

array([[ 6.21509231,  5.35008525,  7.08927833],
       [ 5.55538695,  5.12428184, 10.07094718]])

In [13]:
random.binomial(n= 10, p= 0.5, size= 10)

array([8, 4, 7, 8, 7, 6, 5, 5, 5, 4])

In [14]:
random.binomial(n= 5, p= 0.5, size= 10)

array([4, 1, 1, 3, 3, 3, 3, 4, 3, 3])

In [15]:
random.uniform(size= (2, 3))

array([[0.62848283, 0.59334173, 0.6080244 ],
       [0.95431005, 0.48171862, 0.57300613]])

In [16]:
random.logistic(loc= 1, scale= 2, size= (2, 3))

array([[ 5.41269908,  2.22481486, -2.84992978],
       [ 5.7771669 ,  1.95620199,  1.64038694]])

In [17]:
random.logistic(loc= 7, scale= 2, size= (2, 3))

array([[4.6151455 , 6.23523031, 9.50610517],
       [1.96335035, 9.54171098, 6.30627379]])

In [18]:
random.multinomial(n= 6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

array([1, 1, 0, 0, 3, 1])

In [19]:
random.multinomial(n= 7, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

array([1, 2, 1, 1, 0, 2])

In [20]:
random.multinomial(n= 7, pvals=[1/7, 1/7, 1/7, 1/7, 1/7, 1/7])

array([0, 0, 0, 3, 1, 3])

In [21]:
random.exponential(scale= 2, size= (2, 3))

array([[1.28832454, 1.06877976, 1.3135652 ],
       [1.95443927, 1.84963717, 6.10629509]])

In [22]:
random.chisquare(df= 2, size= (3, 3))

array([[2.16492663, 1.27655682, 0.31063957],
       [1.39737329, 3.34532091, 2.16727234],
       [0.69428327, 2.13548859, 2.59314965]])

In [23]:
random.rayleigh(scale= 2, size= (2, 2))

array([[1.43164731, 3.4068243 ],
       [1.03913033, 2.99826685]])

In [24]:
random.pareto(a= 2, size= (2, 3))

array([[8.87948616, 0.48502883, 0.31477427],
       [0.38454054, 1.70277732, 0.78273273]])

In [25]:
random.zipf(a= 2, size= (3, 2))

array([[ 1,  1],
       [ 1, 11],
       [ 2,  3]])

In [26]:
array_1 = np.array([20, 21, 22, 23, 24, 25])
array_2 = np.array([50, 51, 52, 53, 54, 55])

In [27]:
add_array = np.add(array_1, array_2)
print(add_array)

[70 72 74 76 78 80]


In [28]:
sub_array = np.subtract(array_1, array_2)
print(sub_array)

[-30 -30 -30 -30 -30 -30]


In [29]:
multip_array = np.multiply(array_1, array_2)
print(multip_array)

[1000 1071 1144 1219 1296 1375]


In [30]:
array_1 = np.array([10, 20, 30, 40, 50, 60])
array_2 = np.array([3, 5, 10, 8, 2, 33])

In [31]:
div_array = np.divide(array_1, array_2)
print(div_array)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [32]:
power_array = np.power(array_1, array_2)
print(power_array)

[      1000    3200000  716276736 -520093696       2500          0]


In [33]:
mod_array = np.mod(array_1, array_2)
print(mod_array)

[ 1  0  0  0  0 27]


In [34]:
remainder_array = np.remainder(array_1, array_2)
print(remainder_array)

[ 1  0  0  0  0 27]


In [35]:
divmod_array = np.divmod(array_1, array_2)
print(divmod_array)

(array([ 3,  4,  3,  5, 25,  1]), array([ 1,  0,  0,  0,  0, 27]))


In [36]:
array = np.array([-1, -2, 1, 2, 3, -4])

abs_array = np.absolute(array)
print(abs_array)

[1 2 1 2 3 4]


**==================== NumPy Universal Functions ====================**

In [37]:
array = np.trunc([-3.1666, 3.6667])
print(array)

[-3.  3.]


In [38]:
array = np.fix([-3.1666, 3.6667])
print(array)

[-3.  3.]


In [39]:
array = np.around(3.1666, 2)
print(array)

3.17


In [40]:
array = np.floor([-3.1666, 3.6667])
print(array)

[-4.  3.]


In [41]:
array = np.ceil([-3.1666, 3.6667])
print(array)

[-3.  4.]
