**==================== Numpy ====================**

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'

In [3]:
array = np.array([1, 2, 3, 4, 5, 6, 7])
array

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
type(array)

numpy.ndarray

In [5]:
print(type(array))

<class 'numpy.ndarray'>


**==================== NumPy Array Slicing ====================**

In [6]:
array[1: 5]

array([2, 3, 4, 5])

In [7]:
array[4: ]

array([5, 6, 7])

In [8]:
array[: 4]

array([1, 2, 3, 4])

In [9]:
array[-3: -1]

array([5, 6])

In [10]:
array[1: 5: 2]

array([2, 4])

In [11]:
array[: : 2]

array([1, 3, 5, 7])

In [12]:
array[0: 2]

array([1, 2])

**==================== Dimensions Array ====================**

In [13]:
D_0 = np.array(42) 
D_0.ndim

0

In [14]:
D_0.shape

()

In [15]:
D_0.size

1

In [16]:
D_1 = np.array([1, 2, 3, 4, 5]) 
D_1.ndim

1

In [17]:
D_1.shape

(5,)

In [18]:
D_1.size

5

In [19]:
D_2 = np.array([[1, 2, 3], [4, 5, 6]]) 
D_2.ndim

2

In [20]:
D_2.shape

(2, 3)

In [21]:
D_2.size

6

In [22]:
D_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
D_3.ndim

3

In [23]:
D_3.shape

(2, 2, 3)

In [24]:
D_3.size

12

**==================== NumPy Array Copy vs View ====================**

In [25]:
array = np.array([1, 2, 3, 4, 5])

x = array.copy()
array[0] = 20

print(array)
print(x)

[20  2  3  4  5]
[1 2 3 4 5]


In [26]:
array = np.array([1, 2, 3, 4, 5, 6])

x = array.view()
array[0] = 74

print(array)
print(x)

[74  2  3  4  5  6]
[74  2  3  4  5  6]


In [27]:
x = array.view()
array[1] = 90

print(array)
print(x)

[74 90  3  4  5  6]
[74 90  3  4  5  6]


In [28]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

**==================== joining Numpy Array ====================**

In [29]:
array_concat = np.concatenate((array_1, array_2))

print(array_concat)

[1 2 3 4 5 6]


In [30]:
array_stack = np.stack((array_1, array_2), axis= 1)

print(array_stack)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
array_hstack = np.hstack((array_1, array_2))

print(array_hstack)

[1 2 3 4 5 6]


In [32]:
array_vstack = np.vstack((array_1, array_2))

print(array_vstack)

[[1 2 3]
 [4 5 6]]


In [33]:
array_dstack = np.dstack((array_1, array_2))

print(array_dstack)

[[[1 4]
  [2 5]
  [3 6]]]


**==================== Searching Array ====================**

In [34]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [35]:
np.where(array == 4)

(array([3], dtype=int64),)

In [36]:
np.where(array %  2 == 0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [37]:
np.where(array %  2 == 1)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [38]:
np.searchsorted(array, 8)

7

**==================== Sorting Array ====================**

In [39]:
array = np.array([33, 14, 85, 1, 74, 11])

print(array)
print(np.sort(array))

[33 14 85  1 74 11]
[ 1 11 14 33 74 85]


In [40]:
array = np.array([[5, 1, 10], [12, 3, 7]])

print(array)
print(np.sort(array))

[[ 5  1 10]
 [12  3  7]]
[[ 1  5 10]
 [ 3  7 12]]


In [41]:
array = np.array(["lime", "magenta", "plum", "purple", "gray", "navy blue", "teal", "silver"])

print(array)
print(np.sort(array))

['lime' 'magenta' 'plum' 'purple' 'gray' 'navy blue' 'teal' 'silver']
['gray' 'lime' 'magenta' 'navy blue' 'plum' 'purple' 'silver' 'teal']


In [42]:
array = np.array([True, False, True])

print(array)
print(np.sort(array))

[ True False  True]
[False  True  True]


**==================== Transpose Array ====================**

In [43]:
array = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [44]:
array.transpose()

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

**==================== Empty Array ====================**

In [45]:
np.empty((3, 3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [8.90098127e-307, 6.23054972e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 5.33590898e-322]])

In [46]:
np.empty((3, 3), dtype= int)

array([[4128860, 6029375, 3801155],
       [5570652, 6619251, 7536754],
       [4718684, 6553701, 7929961]])

**==================== Ones Array ====================**

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.ones((3, 4), dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
np.ones((3, 4), dtype= bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

**==================== Zeros Array ====================**

In [51]:
np.zeros(4)

array([0., 0., 0., 0.])

In [52]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.zeros((3, 4), dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
np.zeros((3, 4), dtype= bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])